[mysql]
    type="sql"
    dialect="mysql"
    host="mysql"
    database="dads5001db"
    username="root"
    password="admin"
    port="3306"
[mongodb]
    host="mongodb"
    database="dads5001db"
    username="root"
    password="admin"
    port="27017"
    authSource="admin"